apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: visionflow-prod
  region: us-east-1

autoModeConfig:
  enabled: false

managedNodeGroups:
  - name: visionflow-ng
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: false
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true

iam:
  withOIDC: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: metrics-server
