apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visionflow-prod
resources:
  - ../../base
  - ../../secret.example.yaml
commonLabels:
  environment: prod
replicas:
  - name: visionflow-api
    count: 3
  - name: visionflow-worker
    count: 2
