apiVersion: apps/v1
kind: Deployment
metadata:
  name: visionflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visionflow-worker
  template:
    metadata:
      labels:
        app: visionflow-worker
    spec:
      containers:
        - name: worker
          image: visionflow-worker
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"

